# Generated by Django 4.0.5 on 2022-06-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='provider',
            field=models.ForeignKey(db_column='PROVIDER_ID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='s_provider', to='servicearea.provider'),
            preserve_default=False,
        ),
    ]
