# Generated by Django 4.0.5 on 2022-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0002_servicearea_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, db_column='EMAIL', max_length=254, null=True),
        ),
    ]
