# Generated by Django 4.0.5 on 2022-06-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicearea', '0003_alter_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone_number',
            field=models.BigIntegerField(blank=True, db_column='PHONE_NUMBER', null=True),
        ),
    ]
